export const config = {
  brand: {
    shortName: 'ERC',
    initials: 'ER',
    plantName: 'Elgi Rubber - Coimbatore',
    plantCode: 'ERC-CBE',
    portalName: 'QUALITY SUITE',
    suiteLabel: 'Productivity Suite',
    primaryColor: '#7c3aed',
    primaryDark: '#6d28d9',
    primaryLight: '#c4b5fd',
    address: 'Elgi Rubber Co. Ltd., Coimbatore, Tamil Nadu 641006',
    productionType: 'Automotive Rubber Components',
  },
  company: {
    name: 'Elgi Rubber Company Limited',
    shortName: 'Elgi Rubber',
    initials: 'ER',
    tagline: 'Precision Rubber Engineering Since 1962',
    accentColor: '#7c3aed',
    accentGradient: 'linear-gradient(135deg, #7c3aed, #6d28d9)',
    established: 1962,
    employees: '1,200+',
    plants: 3,
    location: 'Coimbatore, India',
  },
  dashboard: {
    title: 'Elgi Rubber Operations Command Center',
    subtitle: 'Automotive Rubber Components Dashboard',
    kpis: [
      { label: 'Components Produced', value: '86,400', sub: 'This month', icon: 'factory', change: '+7% vs last month', changeType: 'up' },
      { label: 'Quality Pass Rate', value: '99.4%', sub: 'Across all lines', icon: 'verified', change: '+0.1% this week', changeType: 'up' },
      { label: 'Active Orders', value: 243, sub: 'In production pipeline', icon: 'assignment', change: '+11 today', changeType: 'up' },
      { label: 'On-Time Delivery', value: '97.2%', sub: 'Last 30 days', icon: 'local_shipping', change: '+0.5% vs target', changeType: 'up' },
    ],
    chartData: [
      { month: 'Jan', units: 78000, target: 75000 },
      { month: 'Feb', units: 80500, target: 78000 },
      { month: 'Mar', units: 83200, target: 80000 },
      { month: 'Apr', units: 81800, target: 82000 },
      { month: 'May', units: 84600, target: 84000 },
      { month: 'Jun', units: 86400, target: 85000 },
    ],
    modules: [
      { name: 'Moulding', health: 91, color: '#7c3aed' },
      { name: 'Quality', health: 98, color: '#059669' },
      { name: 'Extrusion', health: 87, color: '#0891b2' },
      { name: 'Assembly', health: 89, color: '#d97706' },
    ],
  },
  nav: [
    { id: 'dashboard', name: 'Dashboard', icon: 'dashboard', path: '/' },
    { id: 'products', name: 'Products', icon: 'inventory_2', path: '/products' },
    { id: 'features', name: 'Features', icon: 'star', path: '/features' },
    { id: 'contact', name: 'Contact Us', icon: 'mail', path: '/contact' },
  ],
  products: [
    { id: 'p1', name: 'Brake Hose Assembly', icon: 'precision_manufacturing', color: '#7c3aed', description: 'DOT-approved brake hose assemblies for passenger vehicles and commercial trucks.', tags: ['Safety', 'OEM'] },
    { id: 'p2', name: 'Hydraulic Hose', icon: 'memory', color: '#0891b2', description: 'High-pressure hydraulic hoses for power steering, transmission, and industrial machinery.', tags: ['Hydraulic', 'Industrial'] },
    { id: 'p3', name: 'Coolant Hose Assembly', icon: 'electric_bolt', color: '#059669', description: 'Silicone and EPDM coolant hose assemblies rated up to 200°C for engine thermal management.', tags: ['Thermal', 'Engine'] },
    { id: 'p4', name: 'Air Spring Assembly', icon: 'handyman', color: '#d97706', description: 'Rolling-lobe air springs for heavy commercial vehicles and rail suspension systems.', tags: ['Commercial', 'Rail'] },
    { id: 'p5', name: 'Sealing System', icon: 'sensors', color: '#dc2626', description: 'Custom-moulded rubber seals, O-rings, and gaskets for engine and transmission applications.', tags: ['Sealing', 'Precision'] },
    { id: 'p6', name: 'Turbo Hose Kit', icon: 'engineering', color: '#0e7490', description: 'Silicone intercooler and turbocharger hose kits for high-performance diesel and petrol engines.', tags: ['Turbo', 'Performance'] },
  ],
  features: [
    { icon: 'verified', title: 'IATF 16949 Certified', description: 'Automotive quality management certification with zero-PPM targets and advanced product quality planning.' },
    { icon: 'public', title: 'OEM Direct Supply', description: 'First-fit supplier to Tata Motors, Mahindra, Ashok Leyland, Maruti Suzuki, and Eicher Motors.' },
    { icon: 'precision_manufacturing', title: 'Advanced Compounding', description: 'In-house rubber compound development lab with over 200 proprietary formulations for diverse operating conditions.' },
    { icon: 'recycling', title: 'Green Manufacturing', description: 'ISO 14001 certified plant with solvent-free processes and waste rubber recycling programmes.' },
    { icon: 'groups', title: 'Deep Engineering Expertise', description: '1,200+ engineers and rubber technologists with 60+ years of compound development experience.' },
    { icon: 'speed', title: 'Rapid Prototyping', description: '72-hour prototype-to-sample cycle using 3D-printed moulds for new application development.' },
  ],
  contact: {
    heading: 'Partner with Elgi Rubber',
    subheading: 'Connect with our engineering team to develop custom rubber solutions for your automotive or industrial application.',
    email: 'harshavaradaraj@elgirubber.com',
    phone: '+91 422 430 3000',
    address: 'Elgi Rubber Company Limited, Avinashi Road, Coimbatore - 641 014, Tamil Nadu, India',
    ctaLabel: 'Request a Sample',
  },
};