export const config = {
  data: {
    productionLines: [
      { id:"PL-01", name:"Ring Frame Section A", shift:"A", target:1200, actual:1145, efficiency:95.4, status:"running", operators:18, downtime:12 },
      { id:"PL-02", name:"Ring Frame Section B", shift:"A", target:1200, actual:1180, efficiency:98.3, status:"running", operators:18, downtime:5 },
      { id:"PL-03", name:"Autoconer Floor", shift:"A", target:960, actual:905, efficiency:94.3, status:"running", operators:12, downtime:18 },
      { id:"PL-04", name:"Simplex (Speed Frame)", shift:"B", target:480, actual:468, efficiency:97.5, status:"running", operators:8, downtime:8 },
      { id:"PL-05", name:"Knitting Section", shift:"A", target:320, actual:285, efficiency:89.1, status:"delayed", operators:10, downtime:28 },
      { id:"PL-06", name:"Yarn Dyeing Plant", shift:"B", target:80, actual:78, efficiency:97.5, status:"running", operators:6, downtime:6 },
      { id:"PL-07", name:"Garments Division", shift:"A", target:2400, actual:2240, efficiency:93.3, status:"running", operators:35, downtime:15 },
      { id:"PL-08", name:"Blow Room — Carding", shift:"A", target:600, actual:540, efficiency:90.0, status:"maintenance", operators:6, downtime:42 },
    ],
    weeklyProduction: [
      { week:"W1", planned:155000, actual:150200, scrap:1800, rework:1200, yield:96.9 },
      { week:"W2", planned:158000, actual:154800, scrap:1400, rework:900, yield:97.6 },
      { week:"W3", planned:152000, actual:146500, scrap:2200, rework:1500, yield:95.6 },
      { week:"W4", planned:160000, actual:157200, scrap:1100, rework:700, yield:98.2 },
      { week:"W5", planned:156000, actual:152800, scrap:1600, rework:1000, yield:97.1 },
      { week:"W6", planned:162000, actual:159400, scrap:900, rework:600, yield:98.5 },
    ],
    productMix: [
      { product:"Ring Spun Yarn (Ne 20-40s)", units:1820, revenue:54600, pct:38 },
      { product:"Compact Yarn (Ne 40-80s)", units:940, revenue:47000, pct:20 },
      { product:"Melange Yarn", units:620, revenue:24800, pct:13 },
      { product:"Knit Fabric (kg)", units:1050, revenue:31500, pct:22 },
      { product:"Readymade Garments (pcs)", units:3200, revenue:32000, pct:7 },
    ],
    oeeShiftData: [
      { shift:"6AM", availability:96.2, performance:91.5, quality:99.1, oee:87.4 },
      { shift:"8AM", availability:97.4, performance:93.8, quality:99.3, oee:90.7 },
      { shift:"10AM", availability:95.8, performance:90.2, quality:98.9, oee:85.4 },
      { shift:"12PM", availability:93.5, performance:88.4, quality:98.6, oee:81.5 },
      { shift:"2PM", availability:96.8, performance:92.5, quality:99.0, oee:88.6 },
      { shift:"4PM", availability:97.8, performance:94.2, quality:99.2, oee:91.5 },
      { shift:"6PM", availability:94.1, performance:87.8, quality:98.5, oee:81.3 },
      { shift:"8PM", availability:90.5, performance:84.2, quality:98.1, oee:74.7 },
    ],
    oeeByLine: [
      { line:"Ring Frame Sec A", oee:86.8, target:88 },
      { line:"Ring Frame Sec B", oee:91.2, target:88 },
      { line:"Autoconer Floor", oee:82.4, target:85 },
      { line:"Speed Frame", oee:88.5, target:88 },
      { line:"Knitting Section", oee:75.3, target:82 },
      { line:"Yarn Dyeing", oee:89.7, target:88 },
      { line:"Blow Room", oee:72.5, target:80 },
    ],
    downtimeReasons: [
      { reason:"Planned Maintenance", hours:38, pct:29 },
      { reason:"Yarn Breakage — End Down", hours:24, pct:18 },
      { reason:"Material Changeover", hours:20, pct:15 },
      { reason:"Power Fluctuation", hours:16, pct:12 },
      { reason:"Machine Breakdown", hours:14, pct:11 },
      { reason:"Operator Absence", hours:10, pct:8 },
      { reason:"Others", hours:9, pct:7 },
    ],
    departments: [
      { dept:"Spinning", headcount:185, present:178, onLeave:5, absent:2, overtime:95, avgSkill:3.9, productivity:94 },
      { dept:"Winding", headcount:82, present:79, onLeave:2, absent:1, overtime:48, avgSkill:3.7, productivity:91 },
      { dept:"Knitting", headcount:65, present:61, onLeave:3, absent:1, overtime:35, avgSkill:3.8, productivity:88 },
      { dept:"Quality Control", headcount:32, present:31, onLeave:1, absent:0, overtime:18, avgSkill:4.5, productivity:97 },
      { dept:"Yarn Dyeing", headcount:28, present:27, onLeave:1, absent:0, overtime:22, avgSkill:4.2, productivity:95 },
      { dept:"Garments", headcount:320, present:308, onLeave:9, absent:3, overtime:120, avgSkill:3.5, productivity:91 },
      { dept:"Maintenance", headcount:45, present:43, onLeave:2, absent:0, overtime:65, avgSkill:4.4, productivity:94 },
      { dept:"Raw Material", headcount:18, present:17, onLeave:1, absent:0, overtime:8, avgSkill:3.8, productivity:93 },
    ],
    shiftPattern: [
      { shift:"Shift A (6AM-2PM)", workers:420, efficiency:92.4, output:78500 },
      { shift:"Shift B (2PM-10PM)", workers:380, efficiency:89.8, output:69200 },
      { shift:"Shift C (10PM-6AM)", workers:185, efficiency:85.2, output:31800 },
    ],
    skillMatrix: [
      { name:"Arumugam K", dept:"Spinning", role:"QC Manager", skills:["Uster Tester","Ring Frame Setup","SPC","Count Testing"], level:5, certifications:3, training:"Completed" },
      { name:"Selvakumar R", dept:"Winding", role:"Floor Supervisor", skills:["Autoconer","Splice Testing","Bobbin Handling"], level:4, certifications:2, training:"In Progress" },
      { name:"Murugesan S", dept:"Spinning", role:"Sr. Operator", skills:["Ring Frame Maintenance","Traveller Setting","Drafting System"], level:4, certifications:2, training:"Completed" },
      { name:"Durai V", dept:"Raw Material", role:"Incoming QC Lead", skills:["Bale Sorting","Micronaire Testing","Contamination Check"], level:4, certifications:2, training:"Completed" },
      { name:"Rajan M", dept:"Quality", role:"QC Technician", skills:["Uster Tester","Tenso Jet","SPC Charts","GD&T"], level:5, certifications:3, training:"Completed" },
      { name:"Senthil A", dept:"Knitting", role:"Knitting Technician", skills:["Circular Knitting","Fabric Inspection","GSM Testing"], level:3, certifications:1, training:"Scheduled" },
      { name:"Kannan P", dept:"Mixing", role:"Mixing Operator", skills:["Cotton Blending","Lap Formation","Mixing Ratio Control"], level:4, certifications:2, training:"Completed" },
    ],
    maintenanceOrders: [
      { id:"MO-501", equipment:"Ring Frame #14 — Drafting Zone", type:"Corrective", priority:"high", status:"in-progress", assignee:"Murugesan S", scheduledDate:"2026-05-14", estHours:6, spareParts:"Apron, cots, cradle" },
      { id:"MO-502", equipment:"Autoconer No. 3 — Splicer Unit", type:"Preventive", priority:"medium", status:"scheduled", assignee:"Selvakumar R", scheduledDate:"2026-05-16", estHours:3, spareParts:"Splicer plates, tension spring" },
      { id:"MO-503", equipment:"Blow Room — Blendomat", type:"Breakdown", priority:"critical", status:"open", assignee:"Maintenance Team", scheduledDate:"2026-05-14", estHours:4, spareParts:"Feed roller, motor coupling" },
      { id:"MO-504", equipment:"Uster Tester UT6 Calibration", type:"Calibration", priority:"medium", status:"scheduled", assignee:"Rajan M", scheduledDate:"2026-05-18", estHours:2, spareParts:"Calibration yarn standards" },
      { id:"MO-505", equipment:"Knitting Machine KM-08 — Needle Bed", type:"Preventive", priority:"medium", status:"completed", assignee:"Senthil A", scheduledDate:"2026-05-10", estHours:4, spareParts:"Needles, sinkers" },
      { id:"MO-506", equipment:"Speed Frame SF-12 — Flyer Spindle", type:"Predictive", priority:"high", status:"scheduled", assignee:"Murugesan S", scheduledDate:"2026-05-20", estHours:5, spareParts:"Spindle bearings, flyer arm" },
      { id:"MO-507", equipment:"Overhead Conveyor — Ring Frame Area", type:"Statutory", priority:"high", status:"scheduled", assignee:"External Vendor", scheduledDate:"2026-05-22", estHours:4, spareParts:"Conveyor belt, guide rollers" },
    ],
    equipmentHealth: [
      { name:"Ring Frames (352 units)", health:89, mtbf:480, mttr:1.8, alerts:3 },
      { name:"Autoconers (48 drums)", health:84, mtbf:360, mttr:2.2, alerts:4 },
      { name:"Speed Frames (18 units)", health:91, mtbf:520, mttr:1.5, alerts:1 },
      { name:"Blow Room Line", health:72, mtbf:240, mttr:4.5, alerts:5 },
      { name:"Knitting Machines (24)", health:86, mtbf:400, mttr:2.0, alerts:3 },
      { name:"Uster Testers (6)", health:95, mtbf:720, mttr:0.8, alerts:0 },
    ],
    energyDaily: [
      { hour:"6AM", kwh:2400, cost:16800, solar:0, grid:2400 },
      { hour:"8AM", kwh:4200, cost:29400, solar:380, grid:3820 },
      { hour:"10AM", kwh:5100, cost:35700, solar:620, grid:4480 },
      { hour:"12PM", kwh:4850, cost:33950, solar:740, grid:4110 },
      { hour:"2PM", kwh:5250, cost:36750, solar:680, grid:4570 },
      { hour:"4PM", kwh:4900, cost:34300, solar:420, grid:4480 },
      { hour:"6PM", kwh:3800, cost:26600, solar:90, grid:3710 },
      { hour:"8PM", kwh:2200, cost:15400, solar:0, grid:2200 },
    ],
    energyByDept: [
      { dept:"Ring Frames (Motor load)", kwh:12800, pct:38, cost:89600 },
      { dept:"Autoconers & Winding", kwh:4200, pct:12, cost:29400 },
      { dept:"Blow Room & Cards", kwh:3600, pct:11, cost:25200 },
      { dept:"Knitting Machines", kwh:3200, pct:10, cost:22400 },
      { dept:"Yarn Dyeing Plant", kwh:4400, pct:13, cost:30800 },
      { dept:"Compressed Air & HVAC", kwh:3800, pct:11, cost:26600 },
      { dept:"Garments & Others", kwh:1600, pct:5, cost:11200 },
    ],
    safetyIncidents: [
      { id:"SI-031", date:"2026-05-10", type:"Near Miss", area:"Ring Frame Floor", description:"Oil spill near bobbin trolley path — slip hazard", severity:"low", status:"closed", action:"Non-slip mats installed, housekeeping SOP updated" },
      { id:"SI-030", date:"2026-05-04", type:"First Aid", area:"Autoconer Section", description:"Minor cut from broken bobbin tube edge", severity:"medium", status:"closed", action:"Glove usage made mandatory in winding section" },
      { id:"SI-029", date:"2026-04-28", type:"Near Miss", area:"Blow Room", description:"Belt guard found loose on blendomat feeder", severity:"high", status:"closed", action:"Guard fastening added to daily PM checklist" },
      { id:"SI-028", date:"2026-04-20", type:"Near Miss", area:"Yarn Dyeing", description:"Hot water pipe condensation causing wet floor", severity:"medium", status:"closed", action:"Insulation replaced, drainage improved" },
      { id:"SI-027", date:"2026-04-15", type:"Property Damage", area:"Garments", description:"Sewing machine needle broke — hit guard panel", severity:"low", status:"closed", action:"Needle gauge inspection frequency increased" },
    ],
    safetyMetrics: [
      { month:"Oct", incidents:6, nearMiss:4, firstAid:2, lostTime:0, observations:62 },
      { month:"Nov", incidents:4, nearMiss:3, firstAid:1, lostTime:0, observations:70 },
      { month:"Dec", incidents:5, nearMiss:3, firstAid:1, lostTime:0, observations:68 },
      { month:"Jan", incidents:3, nearMiss:2, firstAid:1, lostTime:0, observations:75 },
      { month:"Feb", incidents:3, nearMiss:2, firstAid:0, lostTime:0, observations:80 },
      { month:"Mar", incidents:2, nearMiss:1, firstAid:1, lostTime:0, observations:45 },
    ],
    ltiFreeDays: 218,
    dashboardKpis: {
      plantOee: "86.2",
      unitsToday: "4820",
      energyMwh: "32.6",
    },
    users: [
      { name:"Somasundaram Kandasamy", role:"Vice President", access:"Full Access" },
      { name:"Arumugam K", role:"QC Manager", access:"Quality + Production + Dashboard" },
      { name:"Selvakumar R", role:"Winding Supervisor", access:"Production + Maintenance + OEE" },
      { name:"Rajan M", role:"QC Technician", access:"Quality + Safety + Dashboard" },
      { name:"Admin", role:"System Admin", access:"Full Access + Settings" },
    ],
    kpiTargets: [
      { label:"OEE Target", value:"88%", icon:"Gauge" },
      { label:"Quality (FPY)", value:"98.5%", icon:"Award" },
      { label:"Machine Utilisation", value:"92%", icon:"CheckCircle" },
      { label:"Specific Energy", value:"1.8 kWh/kg", icon:"Zap" },
      { label:"PM Compliance", value:"95%", icon:"Wrench" },
      { label:"LTI Free Days", value:"365", icon:"Shield" },
    ],
  },

  brand: {
    shortName: 'KPR',
    initials: 'KM',
    plantName: 'KPR Mill - Coimbatore',
    plantCode: 'KPR-CBE',
    portalName: 'QUALITY SUITE',
    suiteLabel: 'Productivity Suite',
    primaryColor: '#0891b2',
    primaryDark: '#0670a2',
    primaryLight: '#67e8f9',
    address: 'KPR Mill Ltd., Coimbatore, Tamil Nadu 641687',
    productionType: 'Textile Yarn Manufacturing',
  },
  company: {
    name: 'KPR Mill Limited',
    shortName: 'KPR Mill',
    initials: 'KM',
    tagline: 'Spinning Excellence Since 1984',
    accentColor: '#0891b2',
    accentGradient: 'linear-gradient(135deg, #0891b2, #0e7490)',
    established: 1984,
    employees: '20,000+',
    plants: 8,
    location: 'Coimbatore, India',
  },
  dashboard: {
    title: 'KPR Mill Operations Command Center',
    subtitle: 'Textile Manufacturing Dashboard',
    kpis: [
      { label: 'Yarn Production (MT)', value: '4,820', sub: 'This month', icon: 'factory', change: '+6% vs last month', changeType: 'up' },
      { label: 'Quality Pass Rate', value: '99.1%', sub: 'Across all lines', icon: 'verified', change: '+0.2% this week', changeType: 'up' },
      { label: 'Active Orders', value: 318, sub: 'In production pipeline', icon: 'assignment', change: '+14 today', changeType: 'up' },
      { label: 'On-Time Delivery', value: '96.3%', sub: 'Last 30 days', icon: 'local_shipping', change: '+0.8% vs target', changeType: 'up' },
    ],
    chartData: [
      { month: 'Jan', units: 4200, target: 4000 },
      { month: 'Feb', units: 4350, target: 4200 },
      { month: 'Mar', units: 4580, target: 4400 },
      { month: 'Apr', units: 4490, target: 4500 },
      { month: 'May', units: 4710, target: 4600 },
      { month: 'Jun', units: 4820, target: 4700 },
    ],
    modules: [
      { name: 'Spinning', health: 92, color: '#0891b2' },
      { name: 'Quality', health: 97, color: '#059669' },
      { name: 'Knitting', health: 88, color: '#7c3aed' },
      { name: 'Garments', health: 85, color: '#d97706' },
    ],
  },
  nav: [
    { id: 'dashboard', name: 'Dashboard', icon: 'dashboard', path: '/' },
    { id: 'products', name: 'Products', icon: 'inventory_2', path: '/products' },
    { id: 'features', name: 'Features', icon: 'star', path: '/features' },
    { id: 'contact', name: 'Contact Us', icon: 'mail', path: '/contact' },
  ],
  products: [
    { id: 'p1', name: 'Ring Spun Yarn', icon: 'precision_manufacturing', color: '#0891b2', description: 'Premium ring spun yarn in Ne 20s to Ne 60s for high-value apparel and home textiles.', tags: ['Apparel', 'Export'] },
    { id: 'p2', name: 'Compact Yarn', icon: 'memory', color: '#059669', description: 'Compact-spun yarn with superior strength and minimal hairiness for technical textiles.', tags: ['Technical', 'Premium'] },
    { id: 'p3', name: 'Melange Yarn', icon: 'electric_bolt', color: '#7c3aed', description: 'Blended melange yarn in cotton and polyester for fashion and sportswear segments.', tags: ['Fashion', 'Sportswear'] },
    { id: 'p4', name: 'Knit Fabric', icon: 'handyman', color: '#d97706', description: 'Single jersey and interlock knit fabrics produced on modern circular knitting lines.', tags: ['Fabric', 'OEM'] },
    { id: 'p5', name: 'Readymade Garments', icon: 'sensors', color: '#dc2626', description: 'Export-quality readymade garments manufactured at KPR Mill integrated garment division.', tags: ['Export', 'Retail'] },
    { id: 'p6', name: 'Denim Fabric', icon: 'engineering', color: '#0e7490', description: 'Stretch and rigid denim fabric woven on rapier looms for global fashion brands.', tags: ['Denim', 'Global'] },
  ],
  features: [
    { icon: 'verified', title: 'Vertically Integrated', description: 'End-to-end integration from cotton ginning through yarn spinning, knitting, dyeing, and garment stitching.' },
    { icon: 'public', title: 'Global Exports', description: 'Supplying premium yarn and garments to leading fashion brands across USA, Europe, and Asia.' },
    { icon: 'precision_manufacturing', title: 'Automation-First', description: 'Over 350,000 spindles equipped with auto-doffing and ring-data monitoring systems.' },
    { icon: 'recycling', title: 'Sustainable Practices', description: 'Zero-liquid discharge plant with captive solar and biomass power for carbon-neutral production.' },
    { icon: 'groups', title: 'Skilled Workforce', description: '20,000+ employees with dedicated training academies producing master spinners and quality technicians.' },
    { icon: 'speed', title: 'Fast Sampling', description: '48-hour yarn sampling turnaround with automated shade matching for buyer approvals.' },
  ],
  contact: {
    heading: 'Partner with KPR Mill',
    subheading: 'Connect with our team to explore yarn sourcing, fabric development, and garment manufacturing partnerships.',
    email: 'somasundaram@kprmill.com',
    phone: '+91 422 430 1000',
    address: 'KPR Mill Limited, Sathy Road, Coimbatore - 641 407, Tamil Nadu, India',
    ctaLabel: 'Request a Sample',
  },
};