export const config = {
  data: {
    ncReports: [
      { id:'NC-001', title:'Brake Hose End Fitting Leak', part:'ER-2200 Brake Hose Assembly', partNo:'BHA-2200-EF', dept:'Assembly', severity:'critical', status:'capa-open', assignee:'Harish R', defectQty:4, due:'2026-05-20', type:'product' },
      { id:'NC-002', title:'Hydraulic Hose Burst Test Failure', part:'ER-1500 Hydraulic Hose', partNo:'HH-1500-BT', dept:'QC', severity:'critical', status:'investigation', assignee:'Sathish P', defectQty:2, due:'2026-05-18', type:'process' },
      { id:'NC-003', title:'Coolant Hose Wall Thinning', part:'Coolant Hose Assembly CHA-900', partNo:'CHA-900-WT', dept:'Extrusion', severity:'major', status:'open', assignee:'Aravind S', defectQty:9, due:'2026-05-25', type:'product' },
      { id:'NC-004', title:'Air Spring Crimping Defect', part:'Air Spring AS-4400', partNo:'AS-4400-CR', dept:'Assembly', severity:'major', status:'closed', assignee:'Shankar M', defectQty:3, due:'2026-05-08', type:'supplier' },
      { id:'NC-005', title:'Sealing System Dimensional OOS', part:'Sealing System SS-300', partNo:'SS-300-DM', dept:'QC', severity:'minor', status:'open', assignee:'Karthikeyan V', defectQty:14, due:'2026-05-28', type:'process' },
      { id:'NC-006', title:'Turbo Hose Surface Blister', part:'Turbo Hose Kit THK-700', partNo:'THK-700-SB', dept:'Vulcanisation', severity:'major', status:'investigation', assignee:'Deepak N', defectQty:6, due:'2026-05-19', type:'product' },
      { id:'NC-007', title:'Hose Assembly Length Deviation', part:'ER-2200 Brake Hose Assembly', partNo:'BHA-2200-LD', dept:'QC', severity:'minor', status:'capa-open', assignee:'Raghu P', defectQty:18, due:'2026-05-22', type:'process' },
      { id:'NC-008', title:'Rubber Compound Hardness OOS', part:'ER-1500 Hydraulic Hose', partNo:'HH-1500-HC', dept:'Compounding', severity:'major', status:'closed', assignee:'Keerthana S', defectQty:5, due:'2026-05-05', type:'supplier' },
    ],
    capaRecords: [
      { id:'CAPA-001', title:'End Fitting Press Tool Calibration', type:'Corrective', dept:'Assembly', status:'In Progress', openedDate:'2026-05-03', targetDate:'2026-05-25', effectiveness:'Pending', actions:['Press force calibration','Tool qualification run','Operator training on torque spec'], completed:2 },
      { id:'CAPA-002', title:'Burst Test Protocol Enhancement', type:'Corrective', dept:'QC', status:'Open', openedDate:'2026-05-10', targetDate:'2026-06-05', effectiveness:'Pending', actions:['Test rig pressure range validation','Frequency increase to 100% sampling'], completed:0 },
      { id:'CAPA-003', title:'Rubber Compound Incoming Inspection SOP', type:'Preventive', dept:'Compounding', status:'Completed', openedDate:'2026-04-12', targetDate:'2026-05-08', effectiveness:'Effective', actions:['Hardness tester procured','Incoming SOP drafted','Certificate of compliance required'], completed:3 },
    ],
    capaMilestones: {
      'CAPA-001': { milestones: [{ label:'Root cause identified', done:true },{ label:'Tooling calibrated', done:true },{ label:'Trial run completed', done:false },{ label:'Effectiveness verified', done:false }] },
      'CAPA-002': { milestones: [{ label:'Protocol drafted', done:true },{ label:'Equipment validation', done:false },{ label:'Implementation', done:false }] },
      'CAPA-003': { milestones: [{ label:'SOP written', done:true },{ label:'Equipment procured', done:true },{ label:'Training done', done:true },{ label:'Closed', done:true }] },
    },
    ncrTrend: [
      { month:'Nov', total:22, product:12, process:7, supplier:3 },
      { month:'Dec', total:19, product:10, process:6, supplier:3 },
      { month:'Jan', total:24, product:13, process:8, supplier:3 },
      { month:'Feb', total:17, product:8, process:6, supplier:3 },
      { month:'Mar', total:14, product:7, process:5, supplier:2 },
      { month:'Apr', total:11, product:5, process:4, supplier:2 },
    ],
    defectPareto: [
      { defect:'Hose End Fitting Leak', count:32, pct:31 },
      { defect:'Wall Thickness OOS', count:24, pct:23 },
      { defect:'Burst Test Failure', count:18, pct:17 },
      { defect:'Dimensional Deviation', count:15, pct:14 },
      { defect:'Surface Blistering', count:10, pct:10 },
      { defect:'Others', count:5, pct:5 },
    ],
    deptBreakdown: [
      { name:'Assembly', value:38 },
      { name:'QC', value:26 },
      { name:'Extrusion', value:18 },
      { name:'Vulcanisation', value:12 },
      { name:'Compounding', value:6 },
    ],
    costOfQuality: [
      { month:'Nov', prevention:38000, appraisal:26000, internal:62000, external:28000 },
      { month:'Dec', prevention:40000, appraisal:28000, internal:55000, external:22000 },
      { month:'Jan', prevention:42000, appraisal:30000, internal:58000, external:25000 },
      { month:'Feb', prevention:45000, appraisal:31000, internal:50000, external:18000 },
      { month:'Mar', prevention:48000, appraisal:33000, internal:44000, external:14000 },
      { month:'Apr', prevention:52000, appraisal:35000, internal:38000, external:10000 },
    ],
    supplierScorecard: [
      { supplier:'Lanxess Rubber', city:'Mumbai', lotsReceived:48, lotsRejected:2, ppm:620, rating:'B', trend:'stable' },
      { supplier:'Eltas Fittings', city:'Coimbatore', lotsReceived:40, lotsRejected:1, ppm:380, rating:'A', trend:'up' },
      { supplier:'Birla Carbon', city:'Pune', lotsReceived:35, lotsRejected:0, ppm:110, rating:'A+', trend:'up' },
      { supplier:'Continental Fitments', city:'Chennai', lotsReceived:28, lotsRejected:2, ppm:890, rating:'C', trend:'down' },
      { supplier:'Parker Hannifin India', city:'Mumbai', lotsReceived:22, lotsRejected:0, ppm:85, rating:'A+', trend:'up' },
    ],
    supplierComparisonData: [
      { supplier:'Lanxess Rubber', ppm:620, rejection:4.2, delivery:93 },
      { supplier:'Eltas Fittings', ppm:380, rejection:2.5, delivery:96 },
      { supplier:'Birla Carbon', ppm:110, rejection:0.0, delivery:99 },
      { supplier:'Continental', ppm:890, rejection:7.1, delivery:87 },
      { supplier:'Parker India', ppm:85, rejection:0.0, delivery:98 },
    ],
    capaEffectiveness: [
      { month:'Nov', closedEffective:6, closedIneffective:2, initiated:9 },
      { month:'Dec', closedEffective:7, closedIneffective:1, initiated:8 },
      { month:'Jan', closedEffective:8, closedIneffective:2, initiated:10 },
      { month:'Feb', closedEffective:6, closedIneffective:0, initiated:8 },
      { month:'Mar', closedEffective:7, closedIneffective:0, initiated:6 },
      { month:'Apr', closedEffective:5, closedIneffective:0, initiated:5 },
    ],
    qualityAlerts: [
      { id:'QA-001', type:'critical', text:'Brake hose end fitting leak rate exceeds 1% — halt and investigate', date:'2026-05-12', status:'open' },
      { id:'QA-002', type:'warning', text:'Continental Fitments PPM trending up — supplier audit scheduled', date:'2026-05-10', status:'open' },
      { id:'QA-003', type:'info', text:'Birla Carbon achieved zero rejections for 3 consecutive months', date:'2026-04-30', status:'closed' },
    ],
    yieldTrendData: [
      { month:'Nov', fpy:92.8, reworkRate:4.9, scrapRate:2.3 },
      { month:'Dec', fpy:93.5, reworkRate:4.2, scrapRate:2.3 },
      { month:'Jan', fpy:93.1, reworkRate:4.5, scrapRate:2.4 },
      { month:'Feb', fpy:94.2, reworkRate:3.8, scrapRate:2.0 },
      { month:'Mar', fpy:95.1, reworkRate:3.2, scrapRate:1.7 },
      { month:'Apr', fpy:95.9, reworkRate:2.8, scrapRate:1.3 },
    ],
    ncrAgingData: [
      { bucket:'0-3 days', count:5, color:'#059669' },
      { bucket:'4-7 days', count:8, color:'#0891b2' },
      { bucket:'8-14 days', count:6, color:'#d97706' },
      { bucket:'15-30 days', count:4, color:'#dc2626' },
      { bucket:'>30 days', count:2, color:'#7c3aed' },
    ],
    inspectionSchedule: [
      { area:'Hose Assembly Line', nextDue:'2026-05-15', freq:'Weekly', status:'due' },
      { area:'Burst Test Lab', nextDue:'2026-05-18', freq:'Bi-weekly', status:'upcoming' },
      { area:'Vulcanisation Bay', nextDue:'2026-05-20', freq:'Weekly', status:'upcoming' },
      { area:'Incoming Rubber QC', nextDue:'2026-05-14', freq:'Daily', status:'due' },
      { area:'Dimensional Metrology', nextDue:'2026-05-21', freq:'Bi-weekly', status:'upcoming' },
    ],
    inspectionHistory: [
      { id:'INS-001', area:'Hose Assembly Line', date:'2026-05-08', result:'pass', inspector:'Harish R', findings:'No issues found' },
      { id:'INS-002', area:'Burst Test Lab', date:'2026-05-04', result:'fail', inspector:'Sathish P', findings:'Hydraulic hose batch #2201 failed burst at 180 bar' },
      { id:'INS-003', area:'Vulcanisation Bay', date:'2026-05-01', result:'conditional', inspector:'Aravind S', findings:'Temperature uniformity — recalibration required' },
      { id:'INS-004', area:'Incoming Rubber QC', date:'2026-05-13', result:'pass', inspector:'Shankar M', findings:'Birla Carbon batch cleared, cert verified' },
    ],
    spcData: [
      { sample:1, ucl:6.5, lcl:5.5, target:6.0, value:5.9 },
      { sample:2, ucl:6.5, lcl:5.5, target:6.0, value:6.1 },
      { sample:3, ucl:6.5, lcl:5.5, target:6.0, value:6.4 },
      { sample:4, ucl:6.5, lcl:5.5, target:6.0, value:5.8 },
      { sample:5, ucl:6.5, lcl:5.5, target:6.0, value:6.2 },
      { sample:6, ucl:6.5, lcl:5.5, target:6.0, value:5.7 },
      { sample:7, ucl:6.5, lcl:5.5, target:6.0, value:6.0 },
      { sample:8, ucl:6.5, lcl:5.5, target:6.0, value:6.3 },
    ],
    users: [
      { id:'u1', name:'Harsha Varadaraj', email:'harshavaradaraj@elgirubber.com', role:'Quality Manager', dept:'Quality', status:'active' },
      { id:'u2', name:'Veluchamy Palaniappan', email:'veluchamyp@in.elgirubber.com', role:'Senior QA Engineer', dept:'QC', status:'active' },
      { id:'u3', name:'Harish R', email:'harish.r@elgirubber.com', role:'QC Inspector', dept:'Assembly', status:'active' },
      { id:'u4', name:'Sathish P', email:'sathish.p@elgirubber.com', role:'Test Lab Engineer', dept:'QC', status:'active' },
      { id:'u5', name:'Aravind S', email:'aravind.s@elgirubber.com', role:'Process Engineer', dept:'Extrusion', status:'active' },
    ],
  },
  brand: {
    shortName: 'ERC',
    initials: 'ER',
    plantName: 'Elgi Rubber - Coimbatore',
    plantCode: 'ERC-CBE',
    portalName: 'QUALITY SUITE',
    suiteLabel: 'Productivity Suite',
    primaryColor: '#7c3aed',
    primaryDark: '#6d28d9',
    primaryLight: '#c4b5fd',
    address: 'Elgi Rubber Co. Ltd., Coimbatore, Tamil Nadu 641006',
    productionType: 'Automotive Rubber Components',
  },
  company: {
    name: 'Elgi Rubber Company Limited',
    shortName: 'Elgi Rubber',
    initials: 'ER',
    tagline: 'Precision Rubber Engineering Since 1962',
    accentColor: '#7c3aed',
    accentGradient: 'linear-gradient(135deg, #7c3aed, #6d28d9)',
    established: 1962,
    employees: '1,200+',
    plants: 3,
    location: 'Coimbatore, India',
  },
  dashboard: {
    title: 'Elgi Rubber Operations Command Center',
    subtitle: 'Automotive Rubber Components Dashboard',
    kpis: [
      { label: 'Components Produced', value: '86,400', sub: 'This month', icon: 'factory', change: '+7% vs last month', changeType: 'up' },
      { label: 'Quality Pass Rate', value: '99.4%', sub: 'Across all lines', icon: 'verified', change: '+0.1% this week', changeType: 'up' },
      { label: 'Active Orders', value: 243, sub: 'In production pipeline', icon: 'assignment', change: '+11 today', changeType: 'up' },
      { label: 'On-Time Delivery', value: '97.2%', sub: 'Last 30 days', icon: 'local_shipping', change: '+0.5% vs target', changeType: 'up' },
    ],
    chartData: [
      { month: 'Jan', units: 78000, target: 75000 },
      { month: 'Feb', units: 80500, target: 78000 },
      { month: 'Mar', units: 83200, target: 80000 },
      { month: 'Apr', units: 81800, target: 82000 },
      { month: 'May', units: 84600, target: 84000 },
      { month: 'Jun', units: 86400, target: 85000 },
    ],
    modules: [
      { name: 'Moulding', health: 91, color: '#7c3aed' },
      { name: 'Quality', health: 98, color: '#059669' },
      { name: 'Extrusion', health: 87, color: '#0891b2' },
      { name: 'Assembly', health: 89, color: '#d97706' },
    ],
  },
  nav: [
    { id: 'dashboard', name: 'Dashboard', icon: 'dashboard', path: '/' },
    { id: 'products', name: 'Products', icon: 'inventory_2', path: '/products' },
    { id: 'features', name: 'Features', icon: 'star', path: '/features' },
    { id: 'contact', name: 'Contact Us', icon: 'mail', path: '/contact' },
  ],
  products: [
    { id: 'p1', name: 'Brake Hose Assembly', icon: 'precision_manufacturing', color: '#7c3aed', description: 'DOT-approved brake hose assemblies for passenger vehicles and commercial trucks.', tags: ['Safety', 'OEM'] },
    { id: 'p2', name: 'Hydraulic Hose', icon: 'memory', color: '#0891b2', description: 'High-pressure hydraulic hoses for power steering, transmission, and industrial machinery.', tags: ['Hydraulic', 'Industrial'] },
    { id: 'p3', name: 'Coolant Hose Assembly', icon: 'electric_bolt', color: '#059669', description: 'Silicone and EPDM coolant hose assemblies rated up to 200°C for engine thermal management.', tags: ['Thermal', 'Engine'] },
    { id: 'p4', name: 'Air Spring Assembly', icon: 'handyman', color: '#d97706', description: 'Rolling-lobe air springs for heavy commercial vehicles and rail suspension systems.', tags: ['Commercial', 'Rail'] },
    { id: 'p5', name: 'Sealing System', icon: 'sensors', color: '#dc2626', description: 'Custom-moulded rubber seals, O-rings, and gaskets for engine and transmission applications.', tags: ['Sealing', 'Precision'] },
    { id: 'p6', name: 'Turbo Hose Kit', icon: 'engineering', color: '#0e7490', description: 'Silicone intercooler and turbocharger hose kits for high-performance diesel and petrol engines.', tags: ['Turbo', 'Performance'] },
  ],
  features: [
    { icon: 'verified', title: 'IATF 16949 Certified', description: 'Automotive quality management certification with zero-PPM targets and advanced product quality planning.' },
    { icon: 'public', title: 'OEM Direct Supply', description: 'First-fit supplier to Tata Motors, Mahindra, Ashok Leyland, Maruti Suzuki, and Eicher Motors.' },
    { icon: 'precision_manufacturing', title: 'Advanced Compounding', description: 'In-house rubber compound development lab with over 200 proprietary formulations for diverse operating conditions.' },
    { icon: 'recycling', title: 'Green Manufacturing', description: 'ISO 14001 certified plant with solvent-free processes and waste rubber recycling programmes.' },
    { icon: 'groups', title: 'Deep Engineering Expertise', description: '1,200+ engineers and rubber technologists with 60+ years of compound development experience.' },
    { icon: 'speed', title: 'Rapid Prototyping', description: '72-hour prototype-to-sample cycle using 3D-printed moulds for new application development.' },
  ],
  contact: {
    heading: 'Partner with Elgi Rubber',
    subheading: 'Connect with our engineering team to develop custom rubber solutions for your automotive or industrial application.',
    email: 'harshavaradaraj@elgirubber.com',
    phone: '+91 422 430 3000',
    address: 'Elgi Rubber Company Limited, Avinashi Road, Coimbatore - 641 014, Tamil Nadu, India',
    ctaLabel: 'Request a Sample',
  },
};