export const config = {
  data: {
    ncReports: [
      { id:'NC-001', title:'Count Variation in Ring Spun Yarn', part:'Ring Spun Yarn Ne 40s', partNo:'RSY-40S-CV', dept:'Spinning', severity:'critical', status:'capa-open', assignee:'Arumugam K', defectQty:18, due:'2026-05-20', type:'process' },
      { id:'NC-002', title:'High End Breakage — Winding Section', part:'Compact Yarn Ne 60s', partNo:'CYN-60S-EB', dept:'Winding', severity:'major', status:'investigation', assignee:'Selvakumar R', defectQty:6, due:'2026-05-22', type:'process' },
      { id:'NC-003', title:'Shade Variation in Melange Yarn', part:'Melange Yarn 30s/1', partNo:'MEL-30S-SV', dept:'Mixing', severity:'minor', status:'open', assignee:'Kannan P', defectQty:3, due:'2026-05-26', type:'product' },
      { id:'NC-004', title:'Twist Per Inch Below Spec', part:'Ring Spun Yarn Ne 20s', partNo:'RSY-20S-TPI', dept:'Spinning', severity:'major', status:'closed', assignee:'Murugesan S', defectQty:12, due:'2026-05-08', type:'process' },
      { id:'NC-005', title:'Cotton Contamination — Lot RCB-220', part:'Raw Cotton Bale', partNo:'RCB-220-CC', dept:'Raw Material', severity:'critical', status:'investigation', assignee:'Durai V', defectQty:5, due:'2026-05-18', type:'supplier' },
      { id:'NC-006', title:'Thin Places > 50% Above Uster Limit', part:'Compact Yarn Ne 80s', partNo:'CYN-80S-TP', dept:'Quality', severity:'major', status:'capa-open', assignee:'Rajan M', defectQty:9, due:'2026-05-21', type:'process' },
      { id:'NC-007', title:'Oil Stain — Knit Fabric Roll', part:'Single Jersey Fabric', partNo:'SJF-180-OS', dept:'Knitting', severity:'minor', status:'open', assignee:'Senthil A', defectQty:2, due:'2026-05-29', type:'product' },
      { id:'NC-008', title:'Bobbin Waste Above 4% Limit', part:'Ring Spun Yarn Ne 30s', partNo:'RSY-30S-BW', dept:'Winding', severity:'minor', status:'closed', assignee:'Babu C', defectQty:0, due:'2026-05-10', type:'process' },
    ],
    capaRecords: [
      { id:'CAPA-001', title:'Count CV% Reduction — Ring Frame Traveller Replacement', type:'Corrective', dept:'Spinning', status:'In Progress', openedDate:'2026-05-02', targetDate:'2026-05-25', effectiveness:'Pending', actions:['Traveller grade trial on 4 frames','Roller pressure audit','Speed frame drafting study'], completed:1 },
      { id:'CAPA-002', title:'Cotton Contamination Control — Bale Management SOP', type:'Corrective', dept:'Raw Material', status:'Completed', openedDate:'2026-04-10', targetDate:'2026-05-05', effectiveness:'Effective', actions:['Bale-by-bale contamination sorting gate installed','Supplier quality agreement updated','Incoming inspection checklist revised'], completed:3 },
      { id:'CAPA-003', title:'Preventive Maintenance — Autoconer End Breakage', type:'Preventive', dept:'Winding', status:'Open', openedDate:'2026-05-06', targetDate:'2026-06-01', effectiveness:'Pending', actions:['Drum groove wear measurement','Tensioner spring replacement schedule','Splice strength study'], completed:0 },
    ],
    capaMilestones: {
      'CAPA-001': { milestones: [{ label:'Root cause identified', done:true },{ label:'Traveller grade trial completed', done:true },{ label:'SOP updated and implemented', done:false },{ label:'Effectiveness verified', done:false }] },
      'CAPA-002': { milestones: [{ label:'Sorting gate installed', done:true },{ label:'Supplier agreement signed', done:true },{ label:'Inspection checklist updated', done:true },{ label:'Closed', done:true }] },
      'CAPA-003': { milestones: [{ label:'Wear measurement done', done:true },{ label:'Replacement schedule defined', done:false },{ label:'Splice study completed', done:false }] },
    },
    ncrTrend: [
      { month:'Nov', total:22, product:10, process:9, supplier:3 },
      { month:'Dec', total:18, product:8, process:7, supplier:3 },
      { month:'Jan', total:24, product:11, process:9, supplier:4 },
      { month:'Feb', total:16, product:7, process:6, supplier:3 },
      { month:'Mar', total:13, product:5, process:6, supplier:2 },
      { month:'Apr', total:10, product:4, process:4, supplier:2 },
    ],
    defectPareto: [
      { defect:'Count Variation', count:32, pct:31 },
      { defect:'End Breakage', count:24, pct:23 },
      { defect:'Thin/Thick Places', count:18, pct:17 },
      { defect:'Cotton Contamination', count:14, pct:13 },
      { defect:'Shade Variation', count:10, pct:10 },
      { defect:'Others', count:6, pct:6 },
    ],
    deptBreakdown: [
      { name:'Spinning', value:38 },
      { name:'Winding', value:27 },
      { name:'Quality', value:18 },
      { name:'Raw Material', value:11 },
      { name:'Knitting', value:6 },
    ],
    costOfQuality: [
      { month:'Nov', prevention:55000, appraisal:32000, internal:68000, external:28000 },
      { month:'Dec', prevention:58000, appraisal:34000, internal:60000, external:22000 },
      { month:'Jan', prevention:60000, appraisal:36000, internal:65000, external:25000 },
      { month:'Feb', prevention:62000, appraisal:37000, internal:55000, external:18000 },
      { month:'Mar', prevention:65000, appraisal:39000, internal:46000, external:14000 },
      { month:'Apr', prevention:68000, appraisal:40000, internal:38000, external:11000 },
    ],
    supplierScorecard: [
      { supplier:'Shanmugavel Cotton', city:'Coimbatore', lotsReceived:48, lotsRejected:2, ppm:620, rating:'B', trend:'stable' },
      { supplier:'Parveen Fibres', city:'Dindigul', lotsReceived:36, lotsRejected:0, ppm:140, rating:'A+', trend:'up' },
      { supplier:'Rieter India', city:'Pune', lotsReceived:12, lotsRejected:0, ppm:90, rating:'A+', trend:'up' },
      { supplier:'LMW Coimbatore', city:'Coimbatore', lotsReceived:22, lotsRejected:1, ppm:510, rating:'A', trend:'up' },
      { supplier:'Truetzschler India', city:'Chennai', lotsReceived:9, lotsRejected:0, ppm:100, rating:'A+', trend:'stable' },
    ],
    supplierComparisonData: [
      { supplier:'Shanmugavel', ppm:620, rejection:4.2, delivery:93 },
      { supplier:'Parveen Fibres', ppm:140, rejection:0.0, delivery:98 },
      { supplier:'Rieter India', ppm:90, rejection:0.0, delivery:99 },
      { supplier:'LMW CBE', ppm:510, rejection:4.5, delivery:94 },
      { supplier:'Truetzschler', ppm:100, rejection:0.0, delivery:97 },
    ],
    capaEffectiveness: [
      { month:'Nov', closedEffective:6, closedIneffective:1, initiated:9 },
      { month:'Dec', closedEffective:7, closedIneffective:0, initiated:7 },
      { month:'Jan', closedEffective:8, closedIneffective:1, initiated:10 },
      { month:'Feb', closedEffective:6, closedIneffective:0, initiated:8 },
      { month:'Mar', closedEffective:7, closedIneffective:0, initiated:6 },
      { month:'Apr', closedEffective:5, closedIneffective:0, initiated:5 },
    ],
    qualityAlerts: [
      { id:'QA-001', type:'critical', text:'Cotton contamination rate above threshold in Lot RCB-220 — quarantine and supplier review initiated', date:'2026-05-12', status:'open' },
      { id:'QA-002', type:'warning', text:'Count CV% rising on Ring Frame No. 14 — traveller inspection scheduled', date:'2026-05-10', status:'open' },
      { id:'QA-003', type:'info', text:'Rieter India achieved zero PPM for Q1 supply — preferred supplier status maintained', date:'2026-04-30', status:'closed' },
    ],
    yieldTrendData: [
      { month:'Nov', fpy:96.2, reworkRate:2.6, scrapRate:1.2 },
      { month:'Dec', fpy:96.8, reworkRate:2.2, scrapRate:1.0 },
      { month:'Jan', fpy:96.5, reworkRate:2.4, scrapRate:1.1 },
      { month:'Feb', fpy:97.2, reworkRate:1.9, scrapRate:0.9 },
      { month:'Mar', fpy:97.8, reworkRate:1.5, scrapRate:0.7 },
      { month:'Apr', fpy:98.4, reworkRate:1.1, scrapRate:0.5 },
    ],
    ncrAgingData: [
      { bucket:'0-3 days', count:3, color:'#059669' },
      { bucket:'4-7 days', count:6, color:'#0891b2' },
      { bucket:'8-14 days', count:4, color:'#d97706' },
      { bucket:'15-30 days', count:2, color:'#dc2626' },
      { bucket:'>30 days', count:1, color:'#7c3aed' },
    ],
    inspectionSchedule: [
      { area:'Ring Frame Section', nextDue:'2026-05-15', freq:'Weekly', status:'due' },
      { area:'Uster Tester Lab', nextDue:'2026-05-18', freq:'Bi-weekly', status:'upcoming' },
      { area:'Autoconer Floor', nextDue:'2026-05-20', freq:'Weekly', status:'upcoming' },
      { area:'Raw Material Store', nextDue:'2026-05-22', freq:'Bi-weekly', status:'upcoming' },
      { area:'Knitting Section', nextDue:'2026-05-14', freq:'Daily', status:'due' },
    ],
    inspectionHistory: [
      { id:'INS-001', area:'Ring Frame Section', date:'2026-05-08', result:'pass', inspector:'Arumugam K', findings:'Count CV% within limits on all 18 frames' },
      { id:'INS-002', area:'Uster Tester Lab', date:'2026-05-04', result:'conditional', inspector:'Selvakumar R', findings:'Calibration due on UT6 tester unit' },
      { id:'INS-003', area:'Autoconer Floor', date:'2026-05-01', result:'pass', inspector:'Kannan P', findings:'Splicer strength and bobbin waste within spec' },
      { id:'INS-004', area:'Raw Material Store', date:'2026-05-13', result:'fail', inspector:'Durai V', findings:'Lot RCB-220 — visible contamination in 5 bales' },
    ],
    spcData: [
      { sample:1, ucl:40.8, lcl:39.2, target:40.0, value:40.1 },
      { sample:2, ucl:40.8, lcl:39.2, target:40.0, value:39.8 },
      { sample:3, ucl:40.8, lcl:39.2, target:40.0, value:40.5 },
      { sample:4, ucl:40.8, lcl:39.2, target:40.0, value:40.2 },
      { sample:5, ucl:40.8, lcl:39.2, target:40.0, value:39.6 },
      { sample:6, ucl:40.8, lcl:39.2, target:40.0, value:40.3 },
      { sample:7, ucl:40.8, lcl:39.2, target:40.0, value:40.7 },
      { sample:8, ucl:40.8, lcl:39.2, target:40.0, value:40.0 },
    ],
    users: [
      { id:'u1', name:'Somasundaram Kandasamy', email:'somasundaram@kprmill.com', role:'Vice President', dept:'Quality', status:'active' },
      { id:'u2', name:'Arumugam K', email:'arumugam.k@kprmill.com', role:'QC Manager', dept:'Spinning', status:'active' },
      { id:'u3', name:'Selvakumar R', email:'selvakumar.r@kprmill.com', role:'QC Inspector', dept:'Winding', status:'active' },
    ],
  },

  brand: {
    shortName: 'KPR',
    initials: 'KM',
    plantName: 'KPR Mill - Coimbatore',
    plantCode: 'KPR-CBE',
    portalName: 'QUALITY SUITE',
    suiteLabel: 'Productivity Suite',
    primaryColor: '#0891b2',
    primaryDark: '#0670a2',
    primaryLight: '#67e8f9',
    address: 'KPR Mill Ltd., Coimbatore, Tamil Nadu 641687',
    productionType: 'Textile Yarn Manufacturing',
  },
  company: {
    name: 'KPR Mill Limited',
    shortName: 'KPR Mill',
    initials: 'KM',
    tagline: 'Spinning Excellence Since 1984',
    accentColor: '#0891b2',
    accentGradient: 'linear-gradient(135deg, #0891b2, #0e7490)',
    established: 1984,
    employees: '20,000+',
    plants: 8,
    location: 'Coimbatore, India',
  },
  dashboard: {
    title: 'KPR Mill Operations Command Center',
    subtitle: 'Textile Manufacturing Dashboard',
    kpis: [
      { label: 'Yarn Production (MT)', value: '4,820', sub: 'This month', icon: 'factory', change: '+6% vs last month', changeType: 'up' },
      { label: 'Quality Pass Rate', value: '99.1%', sub: 'Across all lines', icon: 'verified', change: '+0.2% this week', changeType: 'up' },
      { label: 'Active Orders', value: 318, sub: 'In production pipeline', icon: 'assignment', change: '+14 today', changeType: 'up' },
      { label: 'On-Time Delivery', value: '96.3%', sub: 'Last 30 days', icon: 'local_shipping', change: '+0.8% vs target', changeType: 'up' },
    ],
    chartData: [
      { month: 'Jan', units: 4200, target: 4000 },
      { month: 'Feb', units: 4350, target: 4200 },
      { month: 'Mar', units: 4580, target: 4400 },
      { month: 'Apr', units: 4490, target: 4500 },
      { month: 'May', units: 4710, target: 4600 },
      { month: 'Jun', units: 4820, target: 4700 },
    ],
    modules: [
      { name: 'Spinning', health: 92, color: '#0891b2' },
      { name: 'Quality', health: 97, color: '#059669' },
      { name: 'Knitting', health: 88, color: '#7c3aed' },
      { name: 'Garments', health: 85, color: '#d97706' },
    ],
  },
  nav: [
    { id: 'dashboard', name: 'Dashboard', icon: 'dashboard', path: '/' },
    { id: 'products', name: 'Products', icon: 'inventory_2', path: '/products' },
    { id: 'features', name: 'Features', icon: 'star', path: '/features' },
    { id: 'contact', name: 'Contact Us', icon: 'mail', path: '/contact' },
  ],
  products: [
    { id: 'p1', name: 'Ring Spun Yarn', icon: 'precision_manufacturing', color: '#0891b2', description: 'Premium ring spun yarn in Ne 20s to Ne 60s for high-value apparel and home textiles.', tags: ['Apparel', 'Export'] },
    { id: 'p2', name: 'Compact Yarn', icon: 'memory', color: '#059669', description: 'Compact-spun yarn with superior strength and minimal hairiness for technical textiles.', tags: ['Technical', 'Premium'] },
    { id: 'p3', name: 'Melange Yarn', icon: 'electric_bolt', color: '#7c3aed', description: 'Blended melange yarn in cotton and polyester for fashion and sportswear segments.', tags: ['Fashion', 'Sportswear'] },
    { id: 'p4', name: 'Knit Fabric', icon: 'handyman', color: '#d97706', description: 'Single jersey and interlock knit fabrics produced on modern circular knitting lines.', tags: ['Fabric', 'OEM'] },
    { id: 'p5', name: 'Readymade Garments', icon: 'sensors', color: '#dc2626', description: 'Export-quality readymade garments manufactured at KPR Mill integrated garment division.', tags: ['Export', 'Retail'] },
    { id: 'p6', name: 'Denim Fabric', icon: 'engineering', color: '#0e7490', description: 'Stretch and rigid denim fabric woven on rapier looms for global fashion brands.', tags: ['Denim', 'Global'] },
  ],
  features: [
    { icon: 'verified', title: 'Vertically Integrated', description: 'End-to-end integration from cotton ginning through yarn spinning, knitting, dyeing, and garment stitching.' },
    { icon: 'public', title: 'Global Exports', description: 'Supplying premium yarn and garments to leading fashion brands across USA, Europe, and Asia.' },
    { icon: 'precision_manufacturing', title: 'Automation-First', description: 'Over 350,000 spindles equipped with auto-doffing and ring-data monitoring systems.' },
    { icon: 'recycling', title: 'Sustainable Practices', description: 'Zero-liquid discharge plant with captive solar and biomass power for carbon-neutral production.' },
    { icon: 'groups', title: 'Skilled Workforce', description: '20,000+ employees with dedicated training academies producing master spinners and quality technicians.' },
    { icon: 'speed', title: 'Fast Sampling', description: '48-hour yarn sampling turnaround with automated shade matching for buyer approvals.' },
  ],
  contact: {
    heading: 'Partner with KPR Mill',
    subheading: 'Connect with our team to explore yarn sourcing, fabric development, and garment manufacturing partnerships.',
    email: 'somasundaram@kprmill.com',
    phone: '+91 422 430 1000',
    address: 'KPR Mill Limited, Sathy Road, Coimbatore - 641 407, Tamil Nadu, India',
    ctaLabel: 'Request a Sample',
  },
};