export const config = {
  company: {
    name: 'ZF India — Coimbatore',
    shortName: 'ZF India',
    initials: 'ZF',
    tagline: 'Pioneering Motion Control Solutions',
    accentColor: '#0066cc',
    accentGradient: 'linear-gradient(135deg, #0066cc, #0052a3)',
    established: 2007,
    employees: '6,000+',
    plants: 16,
    location: 'Coimbatore, Tamil Nadu, India',
  },
  dashboard: {
    title: 'ZF India Operations Dashboard',
    subtitle: 'Coimbatore Manufacturing Hub',
    kpis: [
      { label: 'Gearboxes Shipped', value: '1,240', sub: 'This month', icon: 'settings', change: '+14% vs last month', changeType: 'up' },
      { label: 'Wind Capacity (MW)', value: '5,500', sub: 'Annual production capacity', icon: 'wind_power', change: 'World #1 outside China', changeType: 'up' },
      { label: 'Active Orders', value: 186, sub: 'In production pipeline', icon: 'assignment', change: '+22 this week', changeType: 'up' },
      { label: 'Defect Rate', value: '0.04%', sub: 'Last 30 days', icon: 'bug_report', change: '-0.01% vs target', changeType: 'up' },
    ],
    chartData: [
      { month: 'Jan', units: 920, target: 900 },
      { month: 'Feb', units: 980, target: 950 },
      { month: 'Mar', units: 1050, target: 1000 },
      { month: 'Apr', units: 1100, target: 1050 },
      { month: 'May', units: 1180, target: 1100 },
      { month: 'Jun', units: 1240, target: 1150 },
    ],
    modules: [
      { name: 'Wind Gearboxes', health: 96, color: '#0066cc' },
      { name: 'Transmissions', health: 92, color: '#0284c7' },
      { name: 'Axle Systems', health: 88, color: '#0ea5e9' },
      { name: 'Braking & Safety', health: 95, color: '#38bdf8' },
    ],
  },
  nav: [
    { id: 'dashboard', name: 'Dashboard', icon: 'dashboard', path: '/' },
    { id: 'products', name: 'Products', icon: 'inventory_2', path: '/products' },
    { id: 'features', name: 'Capabilities', icon: 'star', path: '/features' },
    { id: 'contact', name: 'Contact Us', icon: 'mail', path: '/contact' },
  ],
  products: [
    {
      id: 'wind', name: 'Wind Turbine Gearboxes', icon: 'wind_power', color: '#0066cc',
      description: 'World-class wind gearbox manufacturing at the largest facility outside China — 5,500 MW annual capacity.',
      tags: ['Wind Energy', 'Renewable', 'Coimbatore'],
    },
    {
      id: 'ergopower', name: 'ERGOPOWER Transmissions', icon: 'settings_input_component', color: '#0052a3',
      description: 'Automatic powershift transmissions for construction machinery delivering up to 15% fuel savings.',
      tags: ['Construction', 'Transmissions', 'Efficiency'],
    },
    {
      id: 'axles', name: 'MULTITRAC Heavy-Duty Axles', icon: 'commute', color: '#0284c7',
      description: 'Advanced axle systems engineered for construction, mining, and heavy-duty industrial equipment.',
      tags: ['Construction', 'Mining', 'Heavy-Duty'],
    },
    {
      id: 'railway', name: 'EcoMet Railway Transmissions', icon: 'train', color: '#0ea5e9',
      description: 'Modular transmission systems for urban metro and mainline railway applications.',
      tags: ['Railway', 'Metro', 'Transit'],
    },
    {
      id: 'braking', name: 'Commercial Vehicle Braking', icon: 'emergency', color: '#1d4ed8',
      description: 'Advanced ABS, EBS, and autonomous emergency braking solutions under WABCO and TRW brands.',
      tags: ['Safety', 'WABCO', 'TRW'],
    },
    {
      id: 'steering', name: 'Driveline & Steering Systems', icon: 'rotate_90_degrees_cw', color: '#7c3aed',
      description: 'Complete driveline, suspension, and steering components under LEMFÖRDER and SACHS brands.',
      tags: ['Driveline', 'SACHS', 'LEMFÖRDER'],
    },
  ],
  features: [
    { icon: 'wind_power', title: 'World-Leading Wind Technology', description: 'Coimbatore hosts the largest wind gearbox manufacturing plant outside China — 5,500 MW annual capacity powering the energy transition.' },
    { icon: 'bolt', title: 'ACE Domain Expertise', description: 'Pioneering Autonomous, Connected, and Electrified (ACE) technology for next-generation mobility and industrial systems.' },
    { icon: 'factory', title: '€20M Investment in India', description: 'ZF's dedicated €20 million Coimbatore facility supports wind, construction, and railway sectors with localised manufacturing.' },
    { icon: 'verified', title: 'Global Tier-1 Quality', description: 'ISO-certified manufacturing with ZF's global quality standards applied at every stage of production.' },
    { icon: 'hub', title: 'Multi-Brand Portfolio', description: 'SACHS, LEMFÖRDER, TRW, WABCO — ZF's portfolio of trusted brands covering every critical system in a vehicle.' },
    { icon: 'engineering', title: '12 Engineering Centres', description: 'ZF India's engineering centres support 12 global locations with R&D, validation, and advanced product development.' },
  ],
  contact: {
    heading: 'Partner with ZF India',
    subheading: 'Discover how ZF's Coimbatore manufacturing hub can support your renewable energy, construction, or automotive requirements.',
    email: 'india.info@zf.com',
    phone: '+91 422 000 0000',
    address: 'ZF Wind Power Coimbatore Pvt. Ltd., SIPCOT Industrial Park, Coimbatore - 641 402, Tamil Nadu, India',
    ctaLabel: 'Request a Demo',
  },
};
